server:
  port: 8000

spring:
  application:
    name: TodoListV2 API
  
  datasource:
    url: jdbc:mariadb://localhost:3306/todoapp
    username: root
    password: Zh777888
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
    operations-sorter: method
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

# Logging
logging:
  level:
    com.todolist.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 